import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { money } from '../types/accounting' // forced sync

export type LedgerPdfInput = {
  companyName: string
  logoDataUrl?: string | null
  title: string
  accountCode: string
  accountName: string
  filters: Array<{ label: string; value: string }>
  fromDate: string | null
  toDate: string | null
  generatedBy: string
  generatedAt: string
  openingBalance: number
  closingBalance: number
  periodDebit: number
  periodCredit: number
  /** Chronological: oldest first, so the last entry is the last row. */
  rows: Array<{
    date: string
    entryNumber: string
    memo: string
    /** Counterpart ledger head(s), plus the journal reference when set. */
    reference?: string
    entity: string
    debit: number
    credit: number
    runningBalance: number
  }>
}

const NAVY: [number, number, number] = [15, 39, 68]

export function buildLedgerPdf(input: LedgerPdfInput): jsPDF {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 14

  if (input.logoDataUrl) {
    try {
      doc.addImage(input.logoDataUrl, 'PNG', 14, y, 16, 16)
    } catch {
      /* ignore bad logo */
    }
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(...NAVY)
  doc.text(input.companyName, input.logoDataUrl ? 34 : 14, y + 6)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(input.title, input.logoDataUrl ? 34 : 14, y + 12)
  y += 22

  doc.setFontSize(9)
  doc.setTextColor(40, 40, 40)
  doc.text(`Account: ${input.accountName || input.accountCode}`, 14, y)
  y += 5
  const range =
    input.fromDate || input.toDate
      ? `${input.fromDate || '…'} → ${input.toDate || '…'}`
      : 'All dates'
  doc.text(`Date range: ${range}`, 14, y)
  y += 5

  const filterLine = input.filters
    .filter((row) => row.value)
    .map((row) => `${row.label}: ${row.value}`)
    .join('   ·   ')
  if (filterLine) {
    const wrapped = doc.splitTextToSize(filterLine, pageWidth - 28)
    doc.text(wrapped, 14, y)
    y += wrapped.length * 4 + 2
  } else {
    y += 2
  }

  const openingLabel = input.fromDate
    ? `Opening balance (before ${input.fromDate})`
    : 'Opening balance'
  const closingLabel = input.toDate
    ? `Closing balance (as at ${input.toDate})`
    : 'Closing balance'
  const balanceRowStyle = {
    fontStyle: 'bold' as const,
    fillColor: [241, 245, 249] as [number, number, number],
    textColor: NAVY,
  }
  const balanceRow = (label: string, amount: number) => [
    { content: '', styles: balanceRowStyle },
    { content: '', styles: balanceRowStyle },
    { content: label, colSpan: 5, styles: balanceRowStyle },
    { content: money(amount), styles: { ...balanceRowStyle, halign: 'right' as const } },
  ]

  autoTable(doc, {
    startY: y,
    head: [
      [
        'Date',
        'Journal',
        'Ledger Head',
        'Description',
        'Party',
        'Debit',
        'Credit',
        'Balance',
      ],
    ],
    body: [
      balanceRow(openingLabel, input.openingBalance),
      ...input.rows.map((row) => [
        row.date.slice(0, 10),
        row.entryNumber,
        row.reference || '—',
        row.memo,
        row.entity,
        row.debit ? money(row.debit) : '',
        row.credit ? money(row.credit) : '',
        money(row.runningBalance),
      ]),
      balanceRow(closingLabel, input.closingBalance),
    ],
    foot: [
      [
        '',
        '',
        'Period totals',
        '',
        '',
        money(input.periodDebit),
        money(input.periodCredit),
        '',
      ],
    ],
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 24 },
      2: { cellWidth: 52 },
      3: { cellWidth: 70 },
      5: { halign: 'right', cellWidth: 24 },
      6: { halign: 'right', cellWidth: 24 },
      7: { halign: 'right', cellWidth: 26 },
    },
    styles: { fontSize: 8, cellPadding: 1.6 },
    headStyles: { fillColor: NAVY, textColor: 255 },
    footStyles: { fillColor: [241, 245, 249], textColor: NAVY, fontStyle: 'bold' },
    margin: { left: 14, right: 14, bottom: 16 },
    didDrawPage: () => {
      const page = doc.getNumberOfPages()
      const height = doc.internal.pageSize.getHeight()
      doc.setFontSize(8)
      doc.setTextColor(90, 101, 120)
      doc.text(
        `Generated by ${input.generatedBy} · ${input.generatedAt}`,
        14,
        height - 8,
      )
      doc.text(`Page ${page}`, pageWidth - 14, height - 8, { align: 'right' })
    },
  })

  return doc
}

export function downloadLedgerPdf(input: LedgerPdfInput): void {
  const doc = buildLedgerPdf(input)
  const stamp = input.generatedAt.slice(0, 10)
  doc.save(`general-ledger-${input.accountCode}-${stamp}.pdf`)
}

/** Blob URL for in-app preview; caller revokes it. */
export function ledgerPdfPreviewUrl(input: LedgerPdfInput): string {
  return URL.createObjectURL(buildLedgerPdf(input).output('blob'))
}
